# Tugas 6 :  Sistem pencarian Query dengan kalimat dalam dokumen dengan penerapan Singular Value Decomposition (SVD)

NAMA : Mohammad Iqbal Surya Ramadhan

NIM  : 210411100002

MATA KULIAH : Pencarian dan Penambangan Web - A

mencari 100 dokumen itu (masukkan 1 kalimat, ketemunya dokumen yg mana)

data tfidf ditransofrmasi menjadi sdikit dimensi menggunakan svd
yg diambil v dan sigma (v tdk diambil smua)(Sebagian dri v)
mentransformasi supaya dikit kolom


cosinus similtas (mirip mendekati 1) boleh pke euclidean

- membuat sistem pencarian dokumen
- reduksi dimensi SVD
- data baru juga di reduksi
- mencari kemiripan ecludian distance

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
import pandas as pd

data_path = ("/content/drive/My Drive/PPWA/report/Tugas-PPWA/Hasil_Prepros.csv")
news_data = pd.read_csv(data_path)

news_data

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,"Nunggak 8 Bulan, Segini Pajak Ford Mustang Mil...","Kamis, 19 Sep 2024 13:05 WIB",Jakarta - Bareskrim Polri menyita aset senilai...,Otomotif,Jakarta Bareskrim Polri menyita aset senilai ...,jakarta bareskrim polri menyita aset senilai ...,"['jakarta', 'bareskrim', 'polri', 'menyita', '...",jakarta bareskrim polri menyita aset senilai r...
1,Bos Ford Kaget usai Jajal Mobil China: Mereka ...,"Kamis, 19 Sep 2024 12:33 WIB","Jakarta - Chief Executive Officer (CEO) Ford, ...",Otomotif,Jakarta Chief Executive Officer CEO Ford Jim ...,jakarta chief executive officer ceo ford jim ...,"['jakarta', 'chief', 'executive', 'officer', '...",jakarta chief executive officer ceo ford jim f...
2,"Tarif Tol Dalam Kota Naik Jadi Segini, Berlaku...","Kamis, 19 Sep 2024 12:08 WIB",Jakarta - Jasa Marga mengumumkan kenaikan tari...,Otomotif,Jakarta Jasa Marga mengumumkan kenaikan tarif...,jakarta jasa marga mengumumkan kenaikan tarif...,"['jakarta', 'jasa', 'marga', 'mengumumkan', 'k...",jakarta jasa marga mengumumkan kenaikan tarif ...
3,Pak RT Aleix Espargaro Tak Sabar Balapan Terak...,"Kamis, 19 Sep 2024 11:40 WIB","Jakarta - Pebalap Aprilia asal Spanyol, Aleix ...",Otomotif,Jakarta Pebalap Aprilia asal Spanyol Aleix Es...,jakarta pebalap aprilia asal spanyol aleix es...,"['jakarta', 'pebalap', 'aprilia', 'asal', 'spa...",jakarta pebalap aprilia spanyol aleix espargar...
4,Angkot Listrik Bakal Diuji Coba di Jakarta,"Kamis, 19 Sep 2024 11:18 WIB",Jakarta - PT Transportasi Jakarta (TransJakart...,Otomotif,Jakarta PT Transportasi Jakarta TransJakarta ...,jakarta pt transportasi jakarta transjakarta ...,"['jakarta', 'pt', 'transportasi', 'jakarta', '...",jakarta pt transportasi jakarta transjakarta k...
...,...,...,...,...,...,...,...,...
95,Suku Bunga BI Dipangkas Jadi 6% Dinilai Berani,"Rabu, 18 Sep 2024 21:15 WIB",Jakarta - Bank Indonesia (BI) memutuskan untuk...,Keuangan,Jakarta Bank Indonesia BI memutuskan untuk me...,jakarta bank indonesia bi memutuskan untuk me...,"['jakarta', 'bank', 'indonesia', 'bi', 'memutu...",jakarta bank indonesia bi memutuskan menurunka...
96,Prabowo Ingatkan Perang Makin Marak hingga Sal...,"Rabu, 18 Sep 2024 21:00 WIB",Jakarta - Presiden terpilih Prabowo Subianto m...,Keuangan,Jakarta Presiden terpilih Prabowo Subianto me...,jakarta presiden terpilih prabowo subianto me...,"['jakarta', 'presiden', 'terpilih', 'prabowo',...",jakarta presiden terpilih prabowo subianto men...
97,"Ditjen Pajak Respons Kabar 6 Juta NPWP Bocor, ...","Rabu, 18 Sep 2024 20:36 WIB",Jakarta - Direktorat Jenderal Pajak (DJP) Keme...,Keuangan,Jakarta Direktorat Jenderal Pajak DJP Kemente...,jakarta direktorat jenderal pajak djp kemente...,"['jakarta', 'direktorat', 'jenderal', 'pajak',...",jakarta direktorat jenderal pajak djp kementer...
98,Buruh Waswas Kisruh di Kadin Pengaruhi Penetap...,"Rabu, 18 Sep 2024 20:30 WIB",Jakarta - Presiden Partai Buruh yang juga Pres...,Keuangan,Jakarta Presiden Partai Buruh yang juga Presi...,jakarta presiden partai buruh yang juga presi...,"['jakarta', 'presiden', 'partai', 'buruh', 'ya...",jakarta presiden partai buruh presiden konfede...
99,PIS Beberkan Rencana Tekan Emisi Karbon di Mas...,"Rabu, 18 Sep 2024 20:19 WIB",Jakarta - Bisnis berkelanjutan dengan emisi ka...,Keuangan,Jakarta Bisnis berkelanjutan dengan emisi kar...,jakarta bisnis berkelanjutan dengan emisi kar...,"['jakarta', 'bisnis', 'berkelanjutan', 'dengan...",jakarta bisnis berkelanjutan emisi karbon rend...

In [29]:
# Ambil kolom dokumen berita
documents = news_data['stopword_removal'].tolist()

**TF-IDF (Term Frequency-Inverse Document Frequency)**

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import euclidean_distances
import pandas as pd
import numpy as np
import joblib

*   TfidfVectorizer adalah alat dari pustaka scikit-learn untuk mengubah kumpulan teks menjadi representasi vektor berbasis Term Frequency-Inverse Document Frequency (TF-IDF)

*   from sklearn.feature_extraction.text adalah modul dalam pustaka scikit-learn yang menyediakan berbagai alat untuk mengekstraksi fitur atau informasi numerik dari data teks (seperti dokumen atau kalimat) agar bisa digunakan dalam model pembelajaran mesin. Salah satu alat penting yang disediakan modul ini adalah TfidfVectorizer, yang digunakan untuk mengonversi teks menjadi representasi numerik berbasis frekuensi.

*   from sklearn.decomposition import TruncatedSVD adalah bagian dari pustaka scikit-learn yang menyediakan alat untuk melakukan reduksi dimensi pada data numerik, terutama matriks besar, dengan menggunakan teknik Truncated Singular Value Decomposition (Truncated SVD). Truncated SVD biasanya diterapkan pada data yang telah diproses menjadi bentuk matriks dengan representasi TF-IDF atau lainnya, terutama pada data teks untuk analisis Latent Semantic Analysis (LSA).

*   Truncated SVD adalah varian dari Singular Value Decomposition (SVD), yang menguraikan matriks menjadi tiga matriks komponen, tetapi dengan hanya menyimpan komponen terbesar. Dalam konteks pembelajaran mesin dan pemrosesan data teks, tujuan utamanya adalah untuk mereduksi dimensi data agar menjadi lebih sederhana, namun tetap mempertahankan informasi penting.

*   from sklearn.metrics.pairwise import euclidean_distances adalah bagian dari pustaka scikit-learn yang digunakan untuk menghitung jarak Euclidean antara pasangan data dalam matriks. Jarak Euclidean adalah ukuran jarak "lurus" antara dua titik dalam ruang dimensi. Di dalam konteks pemrosesan teks atau data numerik, ini sering digunakan untuk mengukur seberapa dekat atau jauh dua dokumen atau dua sampel dalam ruang vektor.

*   euclidean_distances digunakan untuk menghitung jarak Euclidean antara setiap pasangan baris dalam dua matriks. Jika hanya ada satu matriks yang diberikan, euclidean_distances akan menghitung jarak Euclidean antara semua baris dalam matriks tersebut, sehingga menghasilkan matriks jarak.

Matriks jarak Euclidean menunjukkan jarak antara setiap dokumen:

*   Nilai yang lebih kecil mengindikasikan bahwa dua dokumen tersebut lebih mirip secara semantik.

*   Nilai yang lebih besar menunjukkan bahwa dua dokumen memiliki perbedaan yang lebih jauh.

*   pandas adalah pustaka Python yang digunakan untuk manipulasi dan analisis data. Dengan menggunakan pandas, Anda dapat dengan mudah bekerja dengan data yang terstruktur dalam bentuk tabel (DataFrame) serta melakukan operasi seperti pemfilteran, pengelompokan, agregasi, dan transformasi data.

*   numpy adalah pustaka Python yang digunakan untuk komputasi numerik. Pustaka ini menyediakan dukungan untuk array multidimensi dan berbagai fungsi matematis yang efisien untuk memanipulasi data tersebut.

*   Digunakan untuk menyimpan dan memuat objek Python, joblib adalah pustaka Python yang digunakan untuk serialisasi (menyimpan) dan deserialisasi (memuat) objek Python, khususnya yang besar, seperti model machine learning.

In [31]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

# Mendapatkan fitur (kata-kata) dari TF-IDF
tfidf_features = tfidf_vectorizer.get_feature_names_out()

# Mengonversi matriks TF-IDF menjadi DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_features)

# Tampilkan hasil TF-IDF
print("\nHasil TF-IDF dalam bentuk DataFrame:")
tfidf_df

Hasil TF-IDF dalam bentuk DataFrame:

,abang,abdullah,abs,absen,ac,acara,acaraacara,acc,accord,acdkil,...,zenix,zero,zhejiang,ziko,zimbabwe,zona,zoning,zs,zulkifli,zz
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.0,0.0,0.0,0.0,0.114233,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
96,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
97,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.078399,0.0
98,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
99,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.033205,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0


1.   membuat sebuah objek TfidfVectorizer. Ini adalah langkah pertama untuk mengonversi kumpulan dokumen teks menjadi representasi numerik berdasarkan frekuensi kata dengan mempertimbangkan seberapa umum atau jarang kata tersebut dalam koleksi dokumen.

2.   TfidfVectorizer mengubah teks menjadi matriks TF-IDF, yang merupakan representasi numerik dari kata-kata dalam dokumen.

3.   menggunakan metode fit_transform() pada objek tfidf_vectorizer untuk menerapkan TF-IDF ke kumpulan dokumen yang disimpan dalam variabel documents.

4.   Hasilnya, tfidf_matrix adalah matriks yang menyimpan nilai TF-IDF untuk setiap kata dalam setiap dokumen. Setiap baris mewakili satu dokumen, dan setiap kolom mewakili satu kata (fitur) dari kumpulan dokumen.

5.   Dengan menggunakan get_feature_names_out(), kita dapat mengambil daftar kata (fitur) yang telah diidentifikasi oleh TfidfVectorizer. Ini adalah kata-kata unik yang ada dalam kumpulan dokumen.

6.   Variabel tfidf_features sekarang berisi daftar semua kata yang digunakan dalam analisis TF-IDF.

7.   mengonversi matriks TF-IDF (yang awalnya dalam bentuk sparse matrix) menjadi DataFrame menggunakan pd.DataFrame().

8.   Metode toarray() digunakan untuk mengubah sparse matrix menjadi array NumPy, yang kemudian dapat dengan mudah dimasukkan ke dalam DataFrame.

9.   columns=tfidf_features memberikan nama kolom pada DataFrame sesuai dengan kata-kata (fitur) yang ada.

10.    menampilkan DataFrame tfidf_df yang berisi nilai TF-IDF untuk setiap kata di setiap dokumen.

**Singular Value Decomposition (SVD)**

In [32]:
# Menggunakan SVD untuk reduksi dimensi
n_components = 100
svd = TruncatedSVD(n_components=n_components)
svd_matrix = svd.fit_transform(tfidf_matrix)

# Mengubah hasil SVD menjadi DataFrame
svd_df = pd.DataFrame(svd_matrix, columns=[f'feature {i+1}' for i in range(n_components)])

# Menampilkan hasil
print("Hasil reduksi dimensi dengan SVD:")
svd_df

Hasil reduksi dimensi dengan SVD:

,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,feature 10,...,feature 91,feature 92,feature 93,feature 94,feature 95,feature 96,feature 97,feature 98,feature 99,feature 100
0,0.316538,-0.134168,-0.027742,-0.068346,0.032257,-0.037286,0.093471,0.258179,-0.027594,-0.032902,...,-0.002018,-0.033002,-0.006155,-0.021286,0.011730,0.000611,-0.002164,-0.011582,0.001889,0.000812
1,0.231510,-0.131316,-0.092982,0.137206,-0.001500,0.012837,0.014578,0.151100,0.060886,-0.046418,...,0.005756,0.000824,0.015479,0.004884,-0.015367,0.011901,0.002442,-0.000014,-0.000725,-0.000748
2,0.221785,0.019340,0.224015,-0.131731,0.618516,0.553204,0.167706,-0.141715,0.054393,-0.037489,...,0.012262,-0.002920,-0.003075,-0.003878,0.010500,0.009039,0.004980,-0.000812,0.045954,0.176552
3,0.120050,-0.031297,0.347339,0.103173,-0.236697,0.080723,0.003682,-0.095835,-0.027000,-0.053518,...,-0.023483,-0.003203,0.008976,-0.000348,0.004533,-0.000595,0.009531,0.000037,0.001314,-0.001483
4,0.141949,-0.042113,-0.002574,0.086886,0.034181,0.021903,-0.108858,0.087057,0.036474,-0.040637,...,-0.001531,-0.000369,-0.014043,-0.008642,0.000920,-0.006803,0.001787,-0.000661,-0.000705,0.001094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.253979,0.615201,-0.141088,-0.002460,-0.137124,0.081352,0.093642,0.015520,-0.033857,0.058014,...,0.039634,-0.072717,0.020862,-0.021014,0.060300,0.038089,0.003063,0.000433,-0.002443,-0.000326
96,0.134244,0.040500,0.052717,0.058221,0.080514,-0.123454,-0.094995,-0.060807,0.034049,-0.064869,...,-0.001463,0.013231,0.012004,0.009068,-0.002444,-0.004308,-0.001379,-0.001922,0.001588,0.000008
97,0.267603,-0.052670,0.167202,-0.270071,0.125769,-0.405008,0.155715,-0.173776,-0.296645,0.150403,...,0.004413,0.002951,-0.005031,0.001398,0.013459,-0.036855,0.001530,-0.308102,0.002074,0.000282
98,0.069874,0.030880,0.017691,0.008420,0.029645,-0.044422,-0.045202,-0.031068,0.010769,-0.031522,...,-0.003466,-0.004614,0.002227,0.000221,0.000430,0.001409,0.000314,0.002692,-0.000407,-0.000714
99,0.117357,0.025382,0.034103,0.072624,0.050075,-0.053358,-0.259389,0.094414,0.143557,-0.152855,...,-0.024915,-0.003082,-0.005224,-0.001553,0.002198,0.001583,0.001549,-0.001047,-0.001152,0.000398

*   menggunakan SVD (Singular Value Decomposition) untuk reduksi dimensi pada matriks TF-IDF.

*   n_components: Di sini, kita menentukan jumlah komponen utama yang ingin kita ambil dari matriks TF-IDF. Dalam hal ini, kita ingin mengurangi dimensi ke 100 komponen. Jumlah ini bisa disesuaikan tergantung pada data dan tujuan analisis.

*   TruncatedSVD: Ini adalah kelas dari pustaka sklearn.decomposition yang digunakan untuk melakukan SVD dengan cara yang efisien pada data besar dan sparse (seperti matriks TF-IDF). TruncatedSVD melakukan reduksi dimensi dengan cara menyimpan informasi penting dari data dengan mengurangi jumlah dimensi.

*   fit_transform(): Metode ini melakukan dua langkah :

1.   Fit: Menyesuaikan model SVD ke matriks TF-IDF untuk menemukan struktur dan pola.

2.   Transform: Mengubah matriks TF-IDF menjadi bentuk baru (matriks SVD) dengan dimensi yang lebih rendah.

*   svd_matrix: Hasil dari fit_transform() adalah matriks baru yang memiliki dimensi n_samples x n_components. Setiap baris di svd_matrix merepresentasikan dokumen dalam ruang dimensi yang lebih rendah.

*   mengonversi hasil matriks SVD (yang merupakan array NumPy) menjadi sebuah DataFrame menggunakan pandas.

*   pd.DataFrame(svd_matrix, ...): Ini menciptakan DataFrame baru dengan baris yang sama dengan jumlah dokumen dan kolom yang sesuai dengan jumlah komponen yang telah ditentukan (100).

*   daftar komprehensif yang membuat nama kolom sebagai feature 1, feature 2, ..., hingga feature 100. Ini memberikan label pada kolom-kolom baru berdasarkan jumlah komponen.

**Implementasi**

In [33]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

*   import re: Memungkinkan kita menggunakan modul reguler ekspresi (regex) untuk pencarian dan manipulasi string. Ini berguna untuk membersihkan teks, seperti menghapus karakter yang tidak diinginkan.

*   import string: Digunakan untuk mengakses sekumpulan konstanta string, seperti daftar karakter alfabet, digit, dan tanda baca. Ini berguna untuk memfilter atau menghapus karakter tertentu dari teks.

*   from nltk.corpus import stopwords: Mengimpor daftar kata yang umum (stopwords) dari pustaka NLTK. Stopwords adalah kata-kata yang sering muncul dalam bahasa tetapi tidak memiliki makna penting untuk analisis, seperti "dan", "di", "yang", dll.

*   from nltk.tokenize import word_tokenize: Mengimpor fungsi untuk memisahkan (tokenisasi) teks menjadi kata-kata. Tokenisasi adalah langkah awal penting dalam pemrosesan teks.

*   import nltk: Mengimpor pustaka NLTK itu sendiri. Ini adalah pustaka yang sangat kuat untuk  menyediakan berbagai alat dan sumber daya.

*   nltk.download('stopwords'): Mengunduh daftar stopwords yang diperlukan dari repositori NLTK. Ini akan memungkinkan Anda menggunakan daftar kata yang umum dalam bahasa Inggris (atau bahasa lain) untuk membersihkan teks.

*   nltk.download('punkt'): Mengunduh tokenizer yang digunakan untuk memisahkan teks menjadi kata dan kalimat. punkt adalah model untuk memisahkan kalimat dan kata, yang dapat menangani berbagai jenis teks dengan baik.

In [34]:

def preprocess_text(text):
    # Cleaning: Menghapus angka dan tanda baca
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.lower()
    words = word_tokenize(text)

    # Stopword removal
    stop_words = set(stopwords.words("indonesian"))
    words = [word for word in words if word not in stop_words]

    return ' '.join(words)

def search_similar_documents(query_text, top_k=5):
    query_text = preprocess_text(query_text)

    # Transformasi query text
    query_tfidf = tfidf_vectorizer.transform([query_text])
    query_svd = svd.transform(query_tfidf)

    # Hitung jarak Euclidean antara query dan dokumen
    distances = euclidean_distances(query_svd, svd_matrix)

    # Ambil indeks dokumen terdekat
    closest_indices = np.argsort(distances[0])[:top_k]
    similarities = distances[0][closest_indices]

    return closest_indices, similarities

# Input teks dan preprocessing
query_text = input("Masukkan teks: ")
processed_query_text = preprocess_text(query_text)

# Melakukan pencarian dengan teks yang telah dipreproses
top_k = 10
indices, distances = search_similar_documents(processed_query_text, top_k)

# Menampilkan hasil pencarian
print("\nHasil pencarian untuk query:", processed_query_text)
for idx, distance in zip(indices, distances):
    print(f"Dokumen ke-{idx + 1}: {documents[idx]}")
    print(f"Jarak Euclidean: {distance:.4f}\n")

Masukkan teks: kendaraan listrik

Hasil pencarian untuk query: kendaraan listrik
Dokumen ke-42: jakarta menteri investasikepala badan koordinasi penanaman modal rosan roeslani bicara potensi indonesia dilirik investor produsen mobil listrik zaman investor asing ragu berinvestasi ekosistem green energy rendah rosan roslani mengungkap potensi energi terbarukan ebt dimilki indonesia mencapai target net zero emmision energi berpotensi indonesia terbarukan nilainya gigawatt potensi bicara potensi berasal tenaga surya angin hydro arus laut biomass panas bumi lainlainnya detikcom leaders forum indonesia hijau inovasi energi sumber daya manusia hotel st regis jakarta selatan selasa senada direktur riset institute for development of economics and finance indef berly martawardaya menyebut pabrikan mundur lantaran indonesia tertinggal negara kawasan asean penggunaan ebt lihat enggan investasi masuk indonesia supply energi terbarukan berly hadir kesempatan manajemen human capital pln yusuf didi setiarto mengungkap pln berencana membangun asetaset energi hijau indonesia disesuaikan masingmasing wilayah menjemput energi hijau pusatpusat pembangkitan sumatera hydro power aceh sumatera utara sumatera barat asetaset geothermal sulawesi selatan sumatera utara sumatera barat rosan mewantiwanti investor batal menanamkan modalnya indonesia garagara sumber ebt memadai berinvestasi berhubungan tata kelola berkelanjutan berkesinambungan lingkungan hidup salah prioritas utama contohnya bikin ev car manufaktur inginnya ya tenaga energinya energi bersih rosan vice chairman perkumpulan industri kendaraan listrik indonesia periklindo achmad rofiqi kondisi pasar mobil listrik indonesia tahap perkembangan semodern china pemerintah indonesia paket kebijakan infrastruktur mengakomodir investor at least asia tertinggal kondisi combustion engine thailand unggul dibanding indonesia ev open book rofiqi area terdekat head to headnya thailand pemerintah paket menarik investor indonesia mobil listrik china kian mendominasi penjualan mobil asap tanah air merek china kian agresif mengenalkan produk mobil listrik indonesia wuling seres chery dfsk byd disusul merek korea selatan hyundai byd merek jepang bicara produk toyota menyajikan model mobil listrik bzx nissan mengenalkan leaf mobil listrik karpet merah indonesia jenis mobil dikenakan pengenaan tarif penjualan barang mewah ppnbm tertuang peraturan pemerintah nomor pemerintah menaikkan tarif pajak pertambahan nilai ppn dikenakan mobil indonesia harga jual tarif ppn harga on the road otr pemerintah relaksasi mobil listrik dikenakan tarif ppn persen pemerintah insentif luas kendaraan listrik keringanan meliputi pembebasan pajak kendaraan bermotor pkb bea nama kendaraan bermotor bbnkb motor mobil listrik berbasis baterai battery electric vehicles bev dikenakan pajak insentif fiskal insentif nonfiskal kendaraan listrik salah satunya mobil listrik dibebaskan aturan pembatasan kendaraan ganjil genap riardin
Jarak Euclidean: 0.8262

Dokumen ke-2: jakarta chief executive officer ceo ford jim farley chief financial officer ceo ford john lawler mengunjungi china melihatlihat pabrik changan automobile menjajal mobil listrik buatan merek lokal disitat carscoops kamis detail mobil listrik changan tipe dicoba bos ford china kendaraan berjenis sport utility vehicle alias suv lawler duduk kursi kemudi farley kursi penumpang lawler benarbenar terkejut mengemudikan mobil listrik besutan changan farley betapa canggihnya kendaraan jim mobil lawler farley produsen china maju mobil listrik china buatan changan foto doc carscoops farley setuju lawler betapa canggihnya mobil buatan china kabarnya anggota dewan ford mantan eksekutif goldman sachs john thornton fakta ancaman eksistensial farley laporan wall street journal wsj catatan ford bertahuntahun salah brand digemari china penjualan mengalami kenaikan menjalin kemitraan joint venture changan jiangling juli farlet mengumumkan menjual mobil listrik murah rp jutaan china kendaraan entrylevel kabarnya meluncur menantang mobil listrik mungil buatan merek lokal logo ford foto francois lenoirreuters ford merek menolak gagasan mobil full listrik menjual mobil bensin hybrid ford dikabarkan meluncurkan suv truk listrik rencana dibatalkan diundur sfndry
Jarak Euclidean: 0.9067

Dokumen ke-5: jakarta pt transportasi jakarta transjakarta kalinya menguji coba mikro trans alias angkot bertenaga listrik membuktikan perusahaan benarbenar serius beralih kendaraan konvensional kendaraan ramah lingkungan kepala departemen humas csr pt transjakarta ayu wardhani uji coba tahap unit armada mikro trans mengurai detail rute angkot listrik detail tanggal pelaksanaan upaya mewujudkan target pemerintah provinsi dki jakarta persen armada transjakarta bus listrik elektrifikasi transportasi publik ayu wardhani dikutip kamis ayu angkot listrik diuji coba kapasitas penumpang orang kapasitas angkot konvensional dilengkapi air conditioner ac pendingin udara angkot listrik dioperasikan transjakarta basis dfsk gelora e blind van elektrik transjakarta menandatangani nota kesepahaman pt sokonindo automobile agen pemegang merek dfsk indonesia angkutan ramah lingkungan disematkan baterai berkapasitas kwh daya tempuh maksimum km pengecasannya jam fitur fast charging ayu mengklaim berinovasi menghadirkan layanan mikro trans terbaik pelanggan unit mikro trans ac beroperasi delapan rute angkot listrik transjakarta berencana menambah unit armada bus listrik mengoperasikan unit sfnrgr
Jarak Euclidean: 0.9121

Dokumen ke-26: jakarta kemacetan parah puncak bogor jawa barat libur pekan kemarin sorotan pemicu kemacetan kendaraan bermotor membludak jalan menampung kendaraan korlantas polri menilai kemacetan puncak pekan kemarin disebabkan kendaraan melintas ruas jalan puncak melebihi kapasitas korlantas mohon maaf masyarakat berlibur bahagia kemarin tersendat jauhjauh korlantas direktur lintas jajaran indonesia daerahdaerah wisata jawa barat jawa jawa timur diy rencanakan rupa petunjuk arahan bertindak dirgakkum korlantas polri brigjen pol raden slamet santoso dikutip korlantas polri slamet kapasitas rasio penggal jalan gadog perbatasan cianjur km menampung kendaraan melntas rasio jalan ribu kendaraan tanggal kemarin kendaraan melintas jalan raya puncak bogor jawa barat pekan minggu senin total kendaraan masuk kendaraan kendaraan wisata kendaraan masyarakat lokal kendaraan kemacetan puncak kepolisian memprediksi menempatkan ratusan personel polres bogor polda jawa barat korlantas backup personel polres cianjur korlantas menempatkan personel lintas fungsi terkait tim urai tim penjaga pengaturan tim taa tim dikmas diterjunkan penerangan masyarakat menyerobot jalur saksikan live detiksore rgrdry
Jarak Euclidean: 0.9123

Dokumen ke-10: jakarta stnk kendaraan dijual wajib diblokir pendataan kendaraan akurat menghindari pajak progresif menjual kendaraan lupa mengajukan pemblokiran stnk pemblokiran stnk tercantum peraturan kepolisian no pasal ayat aturan pemblokiran data stnk kepentingan pencegahan pengesahan perpanjangan registrasi kendaraan bermotor penggantian stnk penegakan hukum pelanggaran lintas stnk kendaraan dijual disarankan pemblokiran data stnk kabid humas polda jateng kombes pol artanto dikutip laman korlantas polri pemblokiran stnk menghindari pajak progresif dibebankan pemilik kendaraan memiliki kendaraan dibebankan membayar pajak progresif kendaraan dibeli dianggap kendaraan nama pemilik kendaraan dijual membeli kendaraan dikenai pajak progresif memblokir stnk kendaraan dijual pemblokiran stnk penegakan aturan lintas tertib berkaitan penerapan tilang etle diharapkan salah kirim surat konfirmasi tilang data dimiliki akurat dokumen disiapkan blokir stnk pemblokiran mudah pemilik kendaraan menyediakan pernyataan bukti penjualan kendaraan bermaterai melampirkan fotokopi stnk kartu tanda penduduk ktp persyaratan terkumpul tinggal kantor samsat terdekat menyerahkan surat pernyataan kelengkapan fotokopi stnk menyertakan nomor polisi jenis kendaraan disertakan ktp sesuai stnk surat pernyataan kendaraan dijual blokir stnk online wilayah pemblokiran stnk online blokir stnk online wilayah jakarta langkahlangkah blokir stnk online buka registrasi nik ktp pemilik kendaraan klik menu pkb klik menu pelayanan pilih jenis pelayanan blokir kendaraan pilih nomor kendaraan diblokir unggah kelengkapan dokumen klik kirim status pemblokiran dikirim email kolom pkb menghubungi layanan hallo pajak jakarta dryrgr
Jarak Euclidean: 0.9148

Dokumen ke-92: jakarta menteri energi sumber daya mineral esdm bahlil lahadalia pemerintah berencana meningkatkan target konsumsi listrik kapita indonesia kilowatthour kwh mendorong pertumbuhan ekonomi sesuai rencana pemerintahan presiden ri terpilih prabowo subianto bahlil melaporkan presiden joko widodo jokowi target konsumsi listrik kapita indonesia kwh tingkat konsumsi mendorong pertumbuhan ekonomi mencapai target konsumsi kapita listrik kemarin angka kwh lihat pertumbuhan ekonominya bahlil acara iigce dikutip youtube sekretariat presiden rabu dewan energi nasional dpr bahlil pertumbuhan konsumsi listrik kapita kwh mendorong pertumbuhan ekonomi kemarin dewan energi nasional ketua jokowi ketua hariannya dpr memutuskan angka kwh mendorong pertumbuhan ekonomi dasar berencana meningkatkan target konsumsi listrik kapita ri kwh konsumsi listrik nasional mendorong pertumbuhan ekonomi sesuai arah kebijakan presiden terpilih prabowo dorong angka kwh mencapai pertumbuhan ekonomi sejalan arah kebijakan presiden prabowo wakil presiden mas gibran simak video prabowo pede pertumbuhan ekonomi ri tembus airlangga gambasvideo detik fdlfdl
Jarak Euclidean: 0.9904

Dokumen ke-87: jakarta pt pln persero berencana mendorong pengembangan pembangkit listrik tenaga air plta sumatera potensi plta wilayah direktur utama pln darmawan prasodjo sumatera memiliki potensi plta gigawatt gw rencana usaha penyediaan tenaga listrik ruptl pembangunan plta direncanakan megawatt mw ruptl perencanaan ketenagalistrikan nasional merancang membangun megawatt kantor pusat pln jakarta rabu gw masuk perencanaan ruptl darmawan perencanaan memanfaatkan potensi perencanaan memetakan memanfaatkan potensi darmawan kesempatan darmawan menekankan kolaborasi investasi global diterapkan indonesia menghadapi perubahan iklim global negara investasi global internasional energi terbarukan diterapkan indonesia yakinkan tantangan global darmawan mantan perdana menteri australia president international hydropower association iha malcolm turnbull mengungkap keunggulan pembangkit listrik tenaga air plta dibanding pembangkit energi terbarukan plta memiliki kemampuan menghasilkan energi terbarukan tenaga surya tenaga angin tenaga air tenaga air kemampuan menghasilkan energi terbarukan tenaga surya angin kantor pusat pln jakarta rabu pembangkit listrik tenaga surya mengalami pertumbuhan pesat global menurutnya teknologi energi berkembang secepat sinar matahari angin menghasilkan energi listrik matahari bersinar halnya angin bertiup upaya menjadikan energi terbarukan mengalir memacu perekonomian pembangkit listrik tenaga air kuncinya kuncinya pembangkit listrik tenaga air bendunganbendungan dibangun indonesia dunia malaysia simak video inovasi energi terbarukan terobosan plta pt vale indonesia tbk gambasvideo detik acdkil
Jarak Euclidean: 0.9984

Dokumen ke-32: jakarta sedan mewah pabrikan jerman terkenal mahal harga jualnya tembus miliaran biaya penggunaannya kerap dicap mahal sedan mewah full elektrik bmw i terbukti tes detikoto sedan jerman hemat efisien segi konsumsi listriknya beragam pengetesan lakukan sedan mewah full elektrik andalan bmw penggunaan harian bmw i mencatatkan angka konsumsi listrik ratarata km kwh rute bebas hambatan rute tol bmw i mencatatkan angka km kwh konsumsi listrik rataratanya tes lakukan membawa mobil kecepatan ratarata km jam rute kota kecepatan ratarata km jam rute tol dipakai seharihari mobil menakutkan anggaran rumah tangga dites kota tim detikoto mengetes bmw i perjalanan dinas kota tepatnya bandung jakarta akurat tes efisiensi listrik lakukan metode full to full mobil cas penuh dibawa jalan sesampainya tujuan isi penuh didapatkan listrik kwh terisi mengecas mobil penuh lantas kwh didapatkan dibagi jarak tempuhnya yes perjalanan bandung masuk tol jakarta singgah spkly berlokasi bilangan kota parahyangan baterai terisi penuh langsung gerbang tol mengarah barat kota jakarta oh iya pengetesan mobil isi orang penumpang bobot natural gaya berkendaranya natural sporty eco driving karakter jalan tol cipularang bandung jakarta cenderung mayoritas turunan menghadapi etape tanjakan berkelok kondisi jalan beragam kendala bmw i sedan bongsor panjangnya meter lebar meter dibekali motor listrik ganda mobil diklaim bertenaga maksimal hp torsi termbus nm badannya bongsor penggunaan motor listrik ganda mobil melesat diam kecepatan km jam hitungan detik lantas mendukung perjalanan mobil dibekali baterai berkapasitas kwh diklaim kondisi baterai penuh bmw i menempuh km tes konsumsi listrik ratarata bmw i foto muhammad hafizh gemilang sesampainya jakarta melewati melipir rest area bilangan serpong mengecas bmw i dites dicas baterai berkurang layar multi information displaynya mid mengarungi perjalanan km durasi berkendaranya jam menit kecepatan ratarata tes kali km jam midnya perjalanan kali mencatatkan angka konsumsi listrik ratarata km kwh catatan komputer hasil tes full to full tes full to fullnya berjalan km bmw i membutuhkan listrik kwh pengecasannya nggak menit bmw i terisi penuh tes full to full bmw i mencatatkan angka km kwh perjalanan bandung jakarta biaya dikeluarkan mengecas mobil rp biaya administrasi murah mhgdry
Jarak Euclidean: 1.0045

Dokumen ke-49: jakarta mg menjual mobil listrik kembaran wuling air ev cloud ev india mobil listrik wuling rebadge mg comet ev mg windsor ev mg memasarkan model pasar indonesia atl manager creative strategist mg motor indonesia muhamad irvan mustafa mg motor indonesia memasarkan comet windsor indonesia indonesia wuling air ev cloud ev mg comet kembaran wuling air ev foto motoroids model possible masuk masuk temanteman wuling bicara by structure tuh saic motor in support part of sgmw dalamnya wuling irvan wartawan jakarta selasa informasi mobil listrik kembaran wuling air ev cloud ev dipasarkan mg india nama comet ev windsor ev comet ev windsor ev desainnya air ev cloud ev berbeda logonya mg windsor ev kembaran wuling cloud ev foto doc mg motors mg meng copy produkproduk mobil listrik wuling lantaran merek perusahaan holding saic shanghai automotive industry corporation motor perusahaan mg wuling memiliki strategi bisnis berbeda indonesia wuling fokus mobil listrik mungil mobil listrik hatchback mg fokus memasarkan mobil listrik berjenis suv kompak barubaru mg motor indonesia menyasar segmen mobil listrik premium menghadirkan mg cyberster harganya tembus rp miliar luadin
Jarak Euclidean: 1.0131

Dokumen ke-18: jakarta kendaraan mewah disita bandar narkoba jaringan hs alias h senilai rp m ford mustang jeep rubicon motor trail jet ski
Jarak Euclidean: 1.0474

Nilai jarak ini menunjukkan tingkat kemiripan: semakin kecil nilai jaraknya, semakin relevan dokumen tersebut dengan kata kunci. Dengan jarak 0.8262, dokumen ini dianggap cukup relevan dalam konteks pencarian.

**Cleaning:**

*   re.sub(r'\d+', '', text): Menghapus semua angka dari teks menggunakan ekspresi reguler.

*   text.translate(...): Menghapus semua tanda baca dengan menggunakan metode translate.

*   text.lower(): Mengubah semua huruf dalam teks menjadi huruf kecil untuk menghindari perbedaan antara huruf besar dan kecil saat analisis.

*   word_tokenize(text): Memisahkan teks menjadi kata-kata (token).

**Stopword Removal:**

*   stop_words = set(stopwords.words("indonesian")): Mengambil daftar kata-kata umum yang tidak memiliki makna penting dalam konteks analisis.

*   words = [word for word in words if word not in stop_words]: Menggunakan pemahaman daftar untuk menghapus semua kata yang terdapat dalam daftar stopwords.

*   Return: Fungsi mengembalikan string yang terdiri dari kata-kata yang telah diproses, digabungkan kembali menjadi satu kalimat.

**Preprocessing:**

*   query_text = preprocess_text(query_text): Memanggil fungsi preprocess_text untuk membersihkan dan mempersiapkan teks query sebelum analisis.

**Transformasi:**

*   query_tfidf = tfidf_vectorizer.transform([query_text]): Mengubah teks query yang telah diproses menjadi representasi TF-IDF.

*   query_svd = svd.transform(query_tfidf): Mengubah matriks TF-IDF dari query menjadi bentuk yang direduksi dimensinya menggunakan SVD.

**Menghitung Jarak:**

*   distances = euclidean_distances(query_svd, svd_matrix): Menghitung jarak Euclidean antara representasi SVD dari query dan semua dokumen yang ada dalam matriks SVD.

**Mengambil Dokumen Terdekat:**

*   closest_indices = np.argsort(distances[0])[:top_k]: Mengurutkan jarak dari yang terkecil dan mengambil indeks dari top_k dokumen terdekat.

*   similarities = distances[0][closest_indices]: Mengambil jarak dari dokumen terdekat sesuai dengan indeks yang diperoleh.

**Melakukan Pencarian**

*   top_k = 5 : Variabel ini menetapkan jumlah maksimum dokumen yang ingin ditampilkan sebagai hasil pencarian. Dalam hal ini, hanya 5 dokumen terdekat yang akan diambil berdasarkan kesamaan dengan query.

*   indices, distances = search_similar_documents(processed_query_text, top_k):

*   Fungsi search_similar_documents dipanggil dengan argumen processed_query_text dan top_k.

**Menampilkan Hasil Pencarian**

*   print("\nHasil pencarian untuk query:", processed_query_text):

*   print("\nHasil pencarian untuk query:", processed_query_text):

*   for idx, distance in zip(indices, distances):

*   Menggunakan loop untuk iterasi melalui indices (indeks dokumen terdekat) dan distances (jarak Euclidean untuk setiap dokumen).

*   Fungsi zip digunakan untuk menggabungkan dua list ini sehingga kita dapat mengakses elemen yang berpasangan.

*   print(f"Dokumen ke-{idx + 1}: {documents[idx]}"):

*   Menampilkan informasi tentang dokumen terdekat yang ditemukan, termasuk urutan dokumen (dengan menambahkan 1 pada indeks) dan isi dokumen dari list documents.

*   print(f"Jarak Euclidean: {distance:.4f}\n"):

*   Menampilkan jarak Euclidean antara query dan dokumen tersebut, dengan format hingga 4 angka desimal.

In [36]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import euclidean_distances

# Mengunduh stopwords dan tokenizer
nltk.download('stopwords')
nltk.download('punkt')

# Contoh DataFrame news_data (Anda harus menggantinya dengan DataFrame Anda sendiri)
# news_data = pd.DataFrame({
#     'nomor': [...], # Ensure this column exists in your DataFrame
#     'tanggal': [...],
#     'judul': [...],
#     'kategori': [...],
#     'isi': [...],
#     'stopword_removal': [...]
# })

# ... (rest of the code remains the same) ...

# Menampilkan hasil pencarian
print("\nHasil pencarian untuk query:", processed_query_text)
for idx, distance in zip(indices, distances):
    # Ambil informasi dari news_data, using correct column names if different
    # If 'nomor' column doesn't exist, replace with actual column name
    # For example, if the column with document number is named 'id', use:
    # nomor_berita = news_data['id'].iloc[idx]
    nomor_berita = news_data.iloc[idx].get('nomor', idx + 1)  # Get 'nomor' if exists, else default to idx + 1
    tanggal_berita = news_data['tanggal'].iloc[idx]
    judul_berita = news_data['judul'].iloc[idx]
    kategori_berita = news_data['kategori'].iloc[idx]
    isi_berita = news_data['isi'].iloc[idx]

    # Menampilkan informasi berita
    print(f"Dokumen ke-{nomor_berita}:") # Output using retrieved or default nomor_berita
    print(f"Tanggal: {tanggal_berita}")
    print(f"Judul: {judul_berita}")
    print(f"Kategori: {kategori_berita}")
    print(f"Isi Berita: {isi_berita}")
    print(f"Jarak Euclidean: {distance:.4f}\n")

Hasil pencarian untuk query: kendaraan listrik
Dokumen ke-42:
Tanggal: Rabu, 18 Sep 2024 07:12 WIB
Judul: Wanti-wanti Investasi Mobil Listrik Indonesia Kalah dari Thailand
Kategori: Otomotif
Isi Berita: Jakarta - Menteri Investasi/Kepala Badan Koordinasi Penanaman Modal Rosan Roeslani bicara potensi Indonesia dilirik investor produsen mobil listrik. Tapi zaman sekarang investor asing bisa ragu berinvestasi jika ekosistem green energy yang masih rendah. Rosan Roslani mengungkap potensi energi terbarukan (EBT) yang dimilki Indonesia demi mencapai target net zero emmision. "Kalau dilihat energi yang berpotensi untuk di Indonesia baru terbarukan nilainya 3.677 gigawatt potensi, kita bicara potensi yang di mana berasal tenaga surya, angin, hydro, arus laut, biomass, panas bumi dan lain-lainnya," kata dia dalam detikcom Leaders Forum 'Menuju Indonesia Hijau: Inovasi Energi dan Sumber Daya Manusia,' di Hotel St. Regis, Jakarta Selatan, Selasa (17/9/2024). Senada dengan hal tersebut, Direktur Riset Institute for Development of Economics and Finance (Indef) Berly Martawardaya menyebut ada pabrikan yang mundur lantaran Indonesia tertinggal dari negara kawasan ASEAN soal penggunaan EBT. "Kita bisa lihat yang enggan (investasi) masuk Indonesia, karena kita tidak cukup supply energi terbarukan," kata Berly. Hadir dalam kesempatan yang sama, Manajemen Human Capital PLN Yusuf Didi Setiarto, mengungkap PLN berencana untuk membangun aset-aset energi hijau di Indonesia yang disesuaikan dengan masing-masing wilayah. "Kita akan menjemput energi hijau yang ada pusat-pusat pembangkitan seperti Sumatera yang kita tahu ada hydro power di Aceh Sumatera Utara dan beberapa di Sumatera Barat, sedangkan aset-aset geothermal kita di Sulawesi Selatan, Sumatera Utara, Sumatera Barat," kata dia. Rosan mewanti-wanti investor bisa batal menanamkan modalnya ke Indonesia gara-gara sumber EBT yang belum memadai. "Untuk mereka berinvestasi, yang berhubungan dengan tata kelola yang berkelanjutan dan berkesinambungan dari lingkungan hidup, itu menjadi salah prioritas utama. Contohnya mereka mau bikin EV car di sini, harus ada manufaktur. Mereka inginnya ya tenaga energinya dari energi yang bersih," kata Rosan. Vice Chairman Perkumpulan Industri Kendaraan Listrik Indonesia (Periklindo) Achmad Rofiqi menjelaskan lebih lanjut kondisi pasar mobil listrik di Indonesia masih dalam tahap perkembangan, belum semodern China. Nah, pemerintah Indonesia harus membuat paket kebijakan dan infrastruktur supaya bisa mengakomodir para investor. " at least di Asia kita tidak tertinggal, kondisi combustion engine Thailand lebih unggul dibanding Indonesia, sekarang EV masih open book," kata Rofiqi. "Untuk area terdekat head to headnya adalah thailand," kata dia. "Bagaimana pemerintah bisa memberikan paket yang menarik untuk para investor," jelasnya lagi. Di Indonesia, mobil listrik China kian mendominasi penjualan mobil tanpa asap di Tanah Air. Seperti diketahui, belakangan merek China kian agresif mengenalkan produk mobil listrik di Indonesia. Mulai dari Wuling, Seres, Chery, DFSK, hingga BYD. Disusul oleh merek asal Korea Selatan seperti Hyundai dan BYD. Merek Jepang juga ada, namun kalau bicara produk belum banyak. Toyota misalnya baru menyajikan satu model mobil listrik bZ4X. Kemudian ada juga Nissan yang mengenalkan Leaf. Mobil listrik sedang mendapat karpet merah di Indonesia. Jenis mobil ini tidak dikenakan pengenaan tarif penjualan atas barang mewah (PPnBM). Hal ini sudah tertuang dalam Peraturan Pemerintah Nomor 74 Tahun 2021. Pemerintah juga sudah menaikkan tarif Pajak Pertambahan Nilai (PPN) yang dikenakan untuk mobil baru di Indonesia adalah sebesar 11% dari harga jual. Tarif PPN ini biasanya sudah termasuk dalam harga on the road (OTR). Tapi pemerintah memberikan relaksasi bagi mobil listrik dengan hanya dikenakan tarif PPN satu persen. Pemerintah lalu memberikan insentif lebih luas untuk kendaraan listrik. Keringanan itu meliputi pembebasan Pajak Kendaraan Bermotor (PKB) dan Bea Balik Nama Kendaraan Bermotor (BBNKB). Jadi motor dan mobil listrik yang berbasis baterai atau Battery Electric Vehicles (BEV) tidak dikenakan pajak lagi. Tak cuma insentif fiskal, insentif non-fiskal juga diberikan untuk kendaraan listrik. Salah satunya adalah mobil listrik dibebaskan dari aturan pembatasan kendaraan ganjil genap. (riar/din)
Jarak Euclidean: 0.8262

Dokumen ke-2:
Tanggal: Kamis, 19 Sep 2024 12:33 WIB
Judul: Bos Ford Kaget usai Jajal Mobil China: Mereka Lebih Maju!
Kategori: Otomotif
Isi Berita: Jakarta - Chief Executive Officer (CEO) Ford, Jim Farley dan Chief Financial Officer (CEO) Ford, John Lawler belum lama ini mengunjungi China untuk melihat-lihat pabrik Changan Automobile. Bahkan, keduanya sempat menjajal mobil listrik buatan merek lokal tersebut. Disitat dari Carscoops , Kamis (19/9), tak dijelaskan secara detail mobil listrik Changan tipe apa yang dicoba bos Ford di China. Namun, kendaraan tersebut berjenis sport utility vehicle alias SUV. Ketika itu, Lawler duduk di kursi kemudi, sementara Farley di kursi penumpang. Lawler benar-benar terkejut setelah mengemudikan mobil listrik besutan Changan. Dia memberi tahu Farley betapa canggihnya kendaraan tersebut! "Jim, (mobil) ini tidak seperti sebelumnya," kata Lawler kepada Farley. "Mereka (produsen China) lebih maju dari kita!" Mobil listrik China buatan Changan. Foto: Doc. Carscoops. Farley setuju dengan Lawler soal betapa canggihnya mobil buatan China. Bahkan, kabarnya, dia sampai memberi tahu anggota dewan Ford dan mantan eksekutif Goldman Sachs John Thornton mengenai fakta tersebut. "Ini merupakan ancaman eksistensial!" demikian yang disampaikan Farley menurut laporan Wall Street Journal (WSJ). Sebagai catatan, Ford selama bertahun-tahun menjadi salah satu brand paling digemari di China. Penjualan mereka mengalami kenaikan setelah menjalin kemitraan (joint venture) dengan Changan dan Jiangling. Pada Juli lalu, Farlet mengumumkan akan menjual mobil listrik murah di bawah Rp 500 jutaan di China. Kendaraan entry-level tersebut kabarnya meluncur 2,5 tahun lagi dan akan menantang mobil listrik mungil buatan merek lokal. Logo Ford Foto: Francois Lenoir/Reuters Ford merupakan satu dari sedikit merek yang menolak gagasan mobil harus full listrik pada 2030. Mereka menegaskan tetap akan menjual mobil bensin dan hybrid hingga tahun tersebut. Ford sebenarnya sempat dikabarkan akan meluncurkan SUV dan truk listrik pada tahun depan. Namun, rencana tersebut kemudian dibatalkan dan diundur ke tahun 2027. (sfn/dry)
Jarak Euclidean: 0.9067

Dokumen ke-5:
Tanggal: Kamis, 19 Sep 2024 11:18 WIB
Judul: Angkot Listrik Bakal Diuji Coba di Jakarta
Kategori: Otomotif
Isi Berita: Jakarta - PT Transportasi Jakarta (TransJakarta) untuk pertama kalinya akan menguji coba mikro trans alias angkot bertenaga listrik. Hal itu membuktikan perusahaan tersebut benar-benar serius beralih dari kendaraan konvensional ke kendaraan ramah lingkungan. Kepala Departemen Humas dan CSR PT Transjakarta Ayu Wardhani menegaskan uji coba tahap pertama akan dilakukan dalam waktu dekat dengan tiga unit armada mikro trans. Namun, dia tak mengurai lebih detail mengenai rute mana saja yang akan dilalui angkot listrik tersebut. Dia juga tak menjelaskan lebih detail mengenai tanggal pasti pelaksanaan. "Ini bagian dari upaya mewujudkan target Pemerintah Provinsi DKI Jakarta yakni 100 persen armada TransJakarta bus listrik pada 2030 sekaligus menuju elektrifikasi transportasi publik masa depan," kata Ayu Wardhani, dikutip dari Antara , Kamis (19/9). Ayu memastikan, angkot listrik yang diuji coba punya kapasitas penumpang hingga 11 orang. Kapasitas tersebut kurang lebih mirip dengan angkot konvensional. Selain itu, kata dia, seluruhnya sudah dilengkapi air conditioner (AC) atau pendingin udara. Angkot listrik yang dioperasikan TransJakarta menggunakan basis DFSK Gelora E sebagai blind van elektrik. TransJakarta telah menandatangani nota kesepahaman dengan PT Sokonindo Automobile selaku agen pemegang merek DFSK di Indonesia. Angkutan umum ramah lingkungan tersebut disematkan baterai berkapasitas 42 kWh dengan daya tempuh maksimum 300 km. Sementara waktu pengecasannya hanya 2,5 jam dengan fitur fast charging. Ayu mengklaim, pihaknya terus berinovasi guna menghadirkan layanan mikro trans terbaik bagi seluruh pelanggan. Sebelumnya, terdapat sebanyak 180 unit mikro trans AC yang beroperasi di delapan rute. Selain angkot listrik, TransJakarta juga berencana menambah 200 unit armada bus listrik hingga akhir tahun 2024. Sejauh ini, mereka sudah mengoperasikan 100 unit. (sfn/rgr)
Jarak Euclidean: 0.9121

Dokumen ke-26:
Tanggal: Rabu, 18 Sep 2024 15:36 WIB
Judul: Pantesan Macet Total, Segini Jumlah Kendaraan yang Melintas di Puncak
Kategori: Otomotif
Isi Berita: Jakarta - Kemacetan parah di Puncak, Bogor, Jawa Barat, saat libur akhir pekan kemarin menjadi sorotan. Ternyata, pemicu kemacetan ini karena jumlah kendaraan bermotor membludak, sementara jalan tidak bisa menampung sejumlah kendaraan itu. Korlantas Polri menilai kemacetan panjang di Puncak akhir pekan kemarin disebabkan oleh jumlah kendaraan yang melintas ruas jalan Puncak melebihi kapasitas. "Korlantas mohon maaf kepada seluruh masyarakat yang seharusnya berlibur dengan bahagia, namun kemarin agak sedikit tersendat. Walaupun sebenarnya jauh-jauh hari, dari pihak Korlantas bersama para direktur lalu lintas di jajaran seluruh Indonesia, khususnya di daerah-daerah wisata seperti di Jawa Barat, Jawa Tengah, Jawa Timur, dan DIY, sudah kita rencanakan sedemikian rupa melalui petunjuk arahan dan cara bertindak yang ada," kata Dirgakkum Korlantas Polri Brigjen Pol Raden Slamet Santoso dikutip Korlantas Polri. Menurut Slamet, kapasitas rasio penggal jalan, khususnya mulai Gadog sampai perbatasan Cianjur sepanjang 22 km tidak bisa menampung jumlah kendaraan yang melntas. Rasio jalan tersebut adalah 70 ribu kendaraan per hari. "Namun, mulai tanggal kemarin, hampir sebanyak 391.142 kendaraan melintas di Jalan Raya Puncak, Bogor, Jawa Barat selama akhir pekan, yaitu selama tiga hari," katanya. Sedangkan pada hari Minggu dan Senin, total kendaraan yang keluar dan masuk adalah sebanyak 136.351 kendaraan. Ini terdiri dari kendaraan wisata, kendaraan yang digunakan untuk masyarakat lokal, dan kendaraan lainnya. Dalam kemacetan panjang di Puncak, Kepolisian sudah memprediksi dengan menempatkan ratusan personel dari Polres Bogor, Polda Jawa Barat, serta dari Korlantas yang juga telah memberikan backup, serta personel dari Polres Cianjur. "Korlantas sudah menempatkan personel lalu lintas khususnya dan fungsi terkait seperti tim urai, tim penjaga, dan pengaturan, termasuk juga tim TAA. Tim Dikmas juga diterjunkan untuk memberikan penerangan kepada masyarakat supaya tidak menyerobot jalur," ungkapnya. Saksikan Live DetikSore: (rgr/dry)
Jarak Euclidean: 0.9123

Dokumen ke-10:
Tanggal: Kamis, 19 Sep 2024 08:53 WIB
Judul: Kendaraan Sudah Dijual, Jangan Lupa STNK-nya Diblokir Biar Nggak Begini!
Kategori: Otomotif
Isi Berita: Jakarta - STNK kendaraan yang sudah dijual wajib diblokir. Hal ini dilakukan agar pendataan kendaraan jadi lebih akurat sekaligus menghindari pajak progresif. Kamu baru menjual kendaraan? Jangan lupa mengajukan pemblokiran STNK. Pemblokiran STNK ini juga tercantum dalam Peraturan Kepolisian No. 7 Tahun 2021 pasal 87 ayat 3. Dalam aturan itu dijelaskan pemblokiran data STNK dilakukan untuk kepentingan pencegahan pengesahan dan perpanjangan registrasi kendaraan bermotor dan atau penggantian STNK serta penegakan hukum pelanggaran lalu lintas. "STNK kendaraan yang dijual disarankan untuk segera pemblokiran data STNK," kata Kabid Humas Polda Jateng Kombes Pol Artanto dikutip laman Korlantas Polri. Pemblokiran STNK juga dilakukan untuk menghindari pajak progresif yang dibebankan kepada pemilik kendaraan. Seperti diketahui, ketika memiliki lebih dari satu kendaraan, maka kamu dibebankan membayar pajak progresif. Kendaraan yang baru dibeli dianggap sebagai kendaraan kedua jika nama Anda masih merupakan pemilik kendaraan yang dijual. Ketika kamu membeli kendaraan baru, kamu tidak akan dikenai pajak progresif dengan memblokir STNK kendaraan yang dijual. Tak cuma itu, pemblokiran STNK juga bisa membuat penegakan aturan lalu lintas lebih tertib. Terutama berkaitan dengan penerapan tilang ETLE. Dengan demikian diharapkan tak lagi ada kasus salah kirim surat konfirmasi tilang karena data yang dimiliki lebih akurat. Dokumen yang Harus Disiapkan untuk Blokir STNK Untuk melakukan pemblokiran pun caranya mudah. Pemilik kendaraan hanya perlu menyediakan pernyataan atau bukti penjualan kendaraan bermaterai dan melampirkan Fotokopi STNK dan Kartu Tanda Penduduk (KTP). Setelah persyaratan terkumpul, kamu tinggal mendatangi kantor Samsat terdekat lalu menyerahkan surat pernyataan dan kelengkapan tersebut. Bila tak ada fotokopi STNK, kamu cukup menyertakan nomor polisi, jenis kendaraan, disertakan KTP sesuai STNK sekaligus surat pernyataan bahwa kendaraan tersebut memang sudah dijual. Cara Blokir STNK Online Di beberapa wilayah, pemblokiran STNK bisa dilakukan lewat online. Berikut cara blokir STNK online untuk wilayah Jakarta. Langkah-langkah Blokir STNK Online Buka https://pajakonline.jakarta.go.id Registrasi dengan NIK KTP pemilik kendaraan Klik menu PKB Klik menu Pelayanan Pilih jenis Pelayanan Blokir Kendaraan Pilih nomor kendaraan yang ingin diblokir Unggah kelengkapan dokumen Klik kirim. Status pemblokiran akan dikirim melalui email atau bisa dilihat di kolom PKB. Kamu bisa menghubungi layanan Hallo Pajak Jakarta di 1500177. (dry/rgr)
Jarak Euclidean: 0.9148

Dokumen ke-92:
Tanggal: Rabu, 18 Sep 2024 22:00 WIB
Judul: Kejar Target Ekonomi Era Prabowo Tumbuh 8%, Bahlil Mau Kerek Konsumsi Listrik
Kategori: Keuangan
Isi Berita: Jakarta - Menteri Energi dan Sumber Daya Mineral (ESDM) Bahlil Lahadalia mengatakan pemerintah berencana meningkatkan target konsumsi listrik per kapita Indonesia hingga 6.500 kilowatt/hour (kWh) guna mendorong pertumbuhan ekonomi sebesar 8% sesuai rencana pemerintahan Presiden RI terpilih Prabowo Subianto. Pada awalnya Bahlil melaporkan kepada Presiden Joko Widodo (Jokowi) bahwa target konsumsi listrik per kapita Indonesia saat ini hanya 4.000 hingga 5.000 kWh. Di mana mana tingkat konsumsi tersebut hanya mampu mendorong pertumbuhan ekonomi mencapai 5%. "Jadi kami target konsumsi per kapita listrik kemarin di angka 4.000 sampai 5.000 (kWh). Tapi itu kita lihat pertumbuhan ekonominya hanya sampai dengan 5%," kata Bahlil dalam acara IIGCE seperti dikutip dari Youtube Sekretariat Presiden, Rabu (18/9/2024). Kemudian bersama dengan Dewan Energi Nasional dan DPR, Bahlil mengatakan dengan pertumbuhan konsumsi listrik per kapita hingga 5.500 kWh dapat mendorong pertumbuhan ekonomi sebesar 6%. "Kemudian kemarin di Dewan Energi Nasional, kebetulan ini ketua umumnya bapak (Jokowi) saya ketua hariannya, di DPR pak sudah kita memutuskan kalau di angka 5.500 (kWh) itu untuk mendorong pertumbuhan ekonomi 6%," Atas dasar inilah, ia kemudian berencana untuk meningkatkan target konsumsi listrik per kapita RI hingga 6.500 kWh. Sebab dengan begitu konsumsi listrik nasional bisa mendorong pertumbuhan ekonomi sebesar 8%, sesuai dengan arah kebijakan Presiden terpilih Prabowo. "Maka kita dorong ke angka 6.000 sampai 6.500 (kWh) untuk mencapai pertumbuhan ekonomi 8%. Ini sejalan dengan arah kebijakan Pak Presiden Prabowo dan Wakil Presiden Mas Gibran," tandasnya. Simak Video: Prabowo Pede Pertumbuhan Ekonomi RI Bisa Tembus 8%, Ini Kata Airlangga [Gambas:Video 20detik] (fdl/fdl)
Jarak Euclidean: 0.9904

Dokumen ke-87:
Tanggal: Kamis, 19 Sep 2024 06:00 WIB
Judul: Rencana PLN Geber PLTA di Sumatera
Kategori: Keuangan
Isi Berita: Jakarta - PT PLN (Persero) berencana mendorong pengembangan Pembangkit Listrik Tenaga Air (PLTA) di Sumatera. Hal ini mengingat, potensi PLTA di wilayah tersebut sangat besar. Direktur Utama PLN Darmawan Prasodjo mengatakan, Sumatera memiliki potensi PLTA sebesar 6 gigawatt (GW). Namun, dalam Rencana Usaha Penyediaan Tenaga Listrik (RUPTL) yang lama, pembangunan PLTA yang direncanakan hanya 400 megawatt (MW). "Di RUPTL lama, perencanaan ketenagalistrikan nasional, kita merancang dan membangun hanya 400 megawatt," katanya di Kantor Pusat PLN Jakarta, Rabu (18/9/2024). Dia mengatakan, sebanyak 5,6 GW tidak masuk perencanaan dalam RUPTL yang lama. Darmawan menuturkan, dalam perencanaan yang baru, pihaknya akan memanfaatkan segala potensi yang ada. "Dengan perencanaan baru ini, kami tidak hanya akan memetakan, namun akan memanfaatkan setiap potensi yang ada," kata Darmawan. Dalam kesempatan itu, Darmawan menekankan pentingnya kolaborasi. Dia mengatakan, investasi global akan diterapkan di Indonesia untuk menghadapi perubahan iklim yang menjadi masalah global. "Tidak hanya negara ini, namun investasi global internasional dalam energi terbarukan akan diterapkan di Indonesia. Dan saya yakinkan Anda semua, ini adalah tantangan global," ungkap Darmawan. Sementara, Mantan Perdana Menteri Australia sekaligus President International Hydropower Association (IHA) Malcolm Turnbull mengungkap keunggulan pembangkit listrik tenaga air (PLTA) dibanding dengan pembangkit energi terbarukan lainnya. Dia mengatakan, PLTA memiliki kemampuan lebih dalam menghasilkan energi baru terbarukan. "Kita punya tenaga surya, kita punya tenaga angin, namun kita memerlukan tenaga air karena tenaga air lah yang memberikan kemampuan untuk menghasilkan energi terbarukan khususnya, dari tenaga surya dan angin," katanya di Kantor Pusat PLN Jakarta, Rabu (18/9/2024). Dia mengatakan, pembangkit listrik tenaga surya mengalami pertumbuhan yang pesat secara global. Menurutnya, belum ada teknologi energi yang berkembang secepat itu. Namun, dia mengatakan, sinar matahari dan angin tidak ada sepanjang waktu untuk menghasilkan energi listrik. "Matahari tidak bersinar sepanjang waktu seperti halnya angin yang bertiup sepanjang waktu," katanya. Dia mengatakan, diperlukan upaya untuk menjadikan energi terbarukan mengalir sepanjang waktu guna memacu perekonomian. Dia mengatakan, pembangkit listrik tenaga air adalah kuncinya. "Dan kuncinya adalah pembangkit listrik tenaga air. Dan tentu saja bendungan-bendungan besar itulah yang sedang dibangun di Indonesia, di seluruh dunia, di Malaysia," katanya. Simak Video: Inovasi Energi Terbarukan dan Terobosan PLTA dari PT Vale Indonesia Tbk [Gambas:Video 20detik] (acd/kil)
Jarak Euclidean: 0.9984

Dokumen ke-32:
Tanggal: Rabu, 18 Sep 2024 12:33 WIB
Judul: Siapa Bilang Mahal? Segini Biaya Perjalanan Bandung-Jakarta Pakai Sedan Mewah BMW i7
Kategori: Otomotif

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!