NAMA : Mohammad Iqbal Surya Ramadhan

NIM  : 210411100002

MATA KULIAH : Pencarian dan Penambangan Web - A

# Tugas 7 : Klasifikasi Berita Metode Logistic Regression dengan reduksi dimensi deploy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/PPWA/report/Tugas-PPWA/Hasil_Prepros.csv")
df.head()

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal
0,"Nunggak 8 Bulan, Segini Pajak Ford Mustang Mil...","Kamis, 19 Sep 2024 13:05 WIB",Jakarta - Bareskrim Polri menyita aset senilai...,Otomotif,Jakarta Bareskrim Polri menyita aset senilai ...,jakarta bareskrim polri menyita aset senilai ...,"['jakarta', 'bareskrim', 'polri', 'menyita', '...",jakarta bareskrim polri menyita aset senilai r...
1,Bos Ford Kaget usai Jajal Mobil China: Mereka ...,"Kamis, 19 Sep 2024 12:33 WIB","Jakarta - Chief Executive Officer (CEO) Ford, ...",Otomotif,Jakarta Chief Executive Officer CEO Ford Jim ...,jakarta chief executive officer ceo ford jim ...,"['jakarta', 'chief', 'executive', 'officer', '...",jakarta chief executive officer ceo ford jim f...
2,"Tarif Tol Dalam Kota Naik Jadi Segini, Berlaku...","Kamis, 19 Sep 2024 12:08 WIB",Jakarta - Jasa Marga mengumumkan kenaikan tari...,Otomotif,Jakarta Jasa Marga mengumumkan kenaikan tarif...,jakarta jasa marga mengumumkan kenaikan tarif...,"['jakarta', 'jasa', 'marga', 'mengumumkan', 'k...",jakarta jasa marga mengumumkan kenaikan tarif ...
3,Pak RT Aleix Espargaro Tak Sabar Balapan Terak...,"Kamis, 19 Sep 2024 11:40 WIB","Jakarta - Pebalap Aprilia asal Spanyol, Aleix ...",Otomotif,Jakarta Pebalap Aprilia asal Spanyol Aleix Es...,jakarta pebalap aprilia asal spanyol aleix es...,"['jakarta', 'pebalap', 'aprilia', 'asal', 'spa...",jakarta pebalap aprilia spanyol aleix espargar...
4,Angkot Listrik Bakal Diuji Coba di Jakarta,"Kamis, 19 Sep 2024 11:18 WIB",Jakarta - PT Transportasi Jakarta (TransJakart...,Otomotif,Jakarta PT Transportasi Jakarta TransJakarta ...,jakarta pt transportasi jakarta transjakarta ...,"['jakarta', 'pt', 'transportasi', 'jakarta', '...",jakarta pt transportasi jakarta transjakarta k...

Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Transformasi data kategorik
label_encoder = LabelEncoder()
df.loc[:, 'kategori_encoded'] = label_encoder.fit_transform(df['kategori'])

# Menampilkan nilai sebelum dan sesudah konversi
print("\nNilai sebelum dan sesudah konversi:")
print(dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

print("\nDataFrame setelah Label Encoding:")
df

Nilai sebelum dan sesudah konversi:
{'Keuangan': 0, 'Otomotif': 1}

DataFrame setelah Label Encoding:

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,stopword_removal,kategori_encoded
0,"Nunggak 8 Bulan, Segini Pajak Ford Mustang Mil...","Kamis, 19 Sep 2024 13:05 WIB",Jakarta - Bareskrim Polri menyita aset senilai...,Otomotif,Jakarta Bareskrim Polri menyita aset senilai ...,jakarta bareskrim polri menyita aset senilai ...,"['jakarta', 'bareskrim', 'polri', 'menyita', '...",jakarta bareskrim polri menyita aset senilai r...,1
1,Bos Ford Kaget usai Jajal Mobil China: Mereka ...,"Kamis, 19 Sep 2024 12:33 WIB","Jakarta - Chief Executive Officer (CEO) Ford, ...",Otomotif,Jakarta Chief Executive Officer CEO Ford Jim ...,jakarta chief executive officer ceo ford jim ...,"['jakarta', 'chief', 'executive', 'officer', '...",jakarta chief executive officer ceo ford jim f...,1
2,"Tarif Tol Dalam Kota Naik Jadi Segini, Berlaku...","Kamis, 19 Sep 2024 12:08 WIB",Jakarta - Jasa Marga mengumumkan kenaikan tari...,Otomotif,Jakarta Jasa Marga mengumumkan kenaikan tarif...,jakarta jasa marga mengumumkan kenaikan tarif...,"['jakarta', 'jasa', 'marga', 'mengumumkan', 'k...",jakarta jasa marga mengumumkan kenaikan tarif ...,1
3,Pak RT Aleix Espargaro Tak Sabar Balapan Terak...,"Kamis, 19 Sep 2024 11:40 WIB","Jakarta - Pebalap Aprilia asal Spanyol, Aleix ...",Otomotif,Jakarta Pebalap Aprilia asal Spanyol Aleix Es...,jakarta pebalap aprilia asal spanyol aleix es...,"['jakarta', 'pebalap', 'aprilia', 'asal', 'spa...",jakarta pebalap aprilia spanyol aleix espargar...,1
4,Angkot Listrik Bakal Diuji Coba di Jakarta,"Kamis, 19 Sep 2024 11:18 WIB",Jakarta - PT Transportasi Jakarta (TransJakart...,Otomotif,Jakarta PT Transportasi Jakarta TransJakarta ...,jakarta pt transportasi jakarta transjakarta ...,"['jakarta', 'pt', 'transportasi', 'jakarta', '...",jakarta pt transportasi jakarta transjakarta k...,1
...,...,...,...,...,...,...,...,...,...
95,Suku Bunga BI Dipangkas Jadi 6% Dinilai Berani,"Rabu, 18 Sep 2024 21:15 WIB",Jakarta - Bank Indonesia (BI) memutuskan untuk...,Keuangan,Jakarta Bank Indonesia BI memutuskan untuk me...,jakarta bank indonesia bi memutuskan untuk me...,"['jakarta', 'bank', 'indonesia', 'bi', 'memutu...",jakarta bank indonesia bi memutuskan menurunka...,0
96,Prabowo Ingatkan Perang Makin Marak hingga Sal...,"Rabu, 18 Sep 2024 21:00 WIB",Jakarta - Presiden terpilih Prabowo Subianto m...,Keuangan,Jakarta Presiden terpilih Prabowo Subianto me...,jakarta presiden terpilih prabowo subianto me...,"['jakarta', 'presiden', 'terpilih', 'prabowo',...",jakarta presiden terpilih prabowo subianto men...,0
97,"Ditjen Pajak Respons Kabar 6 Juta NPWP Bocor, ...","Rabu, 18 Sep 2024 20:36 WIB",Jakarta - Direktorat Jenderal Pajak (DJP) Keme...,Keuangan,Jakarta Direktorat Jenderal Pajak DJP Kemente...,jakarta direktorat jenderal pajak djp kemente...,"['jakarta', 'direktorat', 'jenderal', 'pajak',...",jakarta direktorat jenderal pajak djp kementer...,0
98,Buruh Waswas Kisruh di Kadin Pengaruhi Penetap...,"Rabu, 18 Sep 2024 20:30 WIB",Jakarta - Presiden Partai Buruh yang juga Pres...,Keuangan,Jakarta Presiden Partai Buruh yang juga Presi...,jakarta presiden partai buruh yang juga presi...,"['jakarta', 'presiden', 'partai', 'buruh', 'ya...",jakarta presiden partai buruh presiden konfede...,0
99,PIS Beberkan Rencana Tekan Emisi Karbon di Mas...,"Rabu, 18 Sep 2024 20:19 WIB",Jakarta - Bisnis berkelanjutan dengan emisi ka...,Keuangan,Jakarta Bisnis berkelanjutan dengan emisi kar...,jakarta bisnis berkelanjutan dengan emisi kar...,"['jakarta', 'bisnis', 'berkelanjutan', 'dengan...",jakarta bisnis berkelanjutan emisi karbon rend...,0

Spliting Data

---

In [ ]:
from sklearn.model_selection import train_test_split

# Split data
x = df ['stopword_removal']
y = df ['kategori_encoded']

print(x)
print(y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)

print("="*50)
print("Jumlah data latih:", len(x_train))
print("Jumlah data uji:", len(x_test))

0     jakarta bareskrim polri menyita aset senilai r...
1     jakarta chief executive officer ceo ford jim f...
2     jakarta jasa marga mengumumkan kenaikan tarif ...
3     jakarta pebalap aprilia spanyol aleix espargar...
4     jakarta pt transportasi jakarta transjakarta k...
                            ...
95    jakarta bank indonesia bi memutuskan menurunka...
96    jakarta presiden terpilih prabowo subianto men...
97    jakarta direktorat jenderal pajak djp kementer...
98    jakarta presiden partai buruh presiden konfede...
99    jakarta bisnis berkelanjutan emisi karbon rend...
Name: stopword_removal, Length: 100, dtype: object
0     1
1     1
2     1
3     1
4     1
     ..
95    0
96    0
97    0
98    0
99    0
Name: kategori_encoded, Length: 100, dtype: int64
==================================================
Jumlah data latih: 80
Jumlah data uji: 20

**TF-IDF (Term Frequency-Inverse Document Frequency)**


---

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Menginisialisasi TfidfVectorizer
vectorizer = TfidfVectorizer()

# Menghitung TF-IDF
tfidf_matrix = vectorizer.fit_transform(x_train)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Inisialisasi TF-IDF Vectorizer
tfidf = TfidfVectorizer()

# Fit dan transform pada data training
x_train_tfidf = tfidf.fit_transform(x_train)

# Transform pada data testing
x_test_tfidf = tfidf.transform(x_test)

# Mendapatkan nama fitur dari TF-IDF
feature_names = tfidf.get_feature_names_out()

# Konversi TF-IDF hasil training ke DataFrame
df_train_tfidf = pd.DataFrame(x_train_tfidf.toarray(), columns=feature_names)

# Konversi TF-IDF hasil testing ke DataFrame
df_test_tfidf = pd.DataFrame(x_test_tfidf.toarray(), columns=feature_names)

# Tampilkan hasil TF-IDF dalam DataFrame
print("TF-IDF untuk data training:")
df_train_tfidf

TF-IDF untuk data training:

,abdullah,abs,absen,ac,acara,acaraacara,accord,acdkil,acdrrd,aceh,...,zainul,zaman,zeekr,zero,ziko,zimbabwe,zona,zs,zulkifli,zz
0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.046091,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
76,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
77,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
78,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
79,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.081968,0.0,0.0,0.0

Reduksi dimensi

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [ ]:
# Menggunakan SVD untuk reduksi dimensi
n_components = 80
svd = TruncatedSVD(n_components=n_components)
svd_matrix = svd.fit_transform(x_train_tfidf)

# Mengubah svd_matrix menjadi DataFrame
df_svd = pd.DataFrame(svd_matrix, columns=[f"component_{i+1}" for i in range(n_components)])
df_svd

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,...,component_71,component_72,component_73,component_74,component_75,component_76,component_77,component_78,component_79,component_80
0,0.091560,-0.019063,0.011164,-0.018241,0.019139,-0.025414,0.079120,-0.058909,-0.084271,-0.104787,...,0.019187,0.007757,-0.034518,-0.019310,0.003535,0.004644,-0.007349,0.000773,0.000761,0.000987
1,0.175494,-0.019489,-0.085935,0.069409,-0.036462,-0.236413,-0.005788,0.073218,0.028822,-0.230423,...,-0.016406,0.032665,0.002974,0.020961,0.024568,0.023850,0.024382,-0.000788,0.008370,-0.000437
2,0.123260,-0.105379,-0.041857,-0.323761,-0.282555,0.062119,-0.008368,-0.009278,-0.055081,-0.133322,...,0.023977,0.015085,0.003931,0.000378,-0.006808,-0.001592,0.007250,-0.024652,0.000611,0.000570
3,0.109109,-0.025951,-0.027950,-0.034425,0.013998,-0.079027,0.136876,0.004505,-0.176790,0.069585,...,0.013114,-0.010175,0.007790,0.004572,0.028844,-0.004470,-0.000176,0.000513,0.004628,0.000004
4,0.027464,-0.023058,0.010050,-0.002917,-0.001103,0.009394,0.031792,-0.075905,0.052905,-0.056340,...,0.007126,0.003454,-0.001350,0.003389,-0.002637,-0.000854,-0.001738,0.000556,-0.000371,0.000202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.116021,-0.104935,-0.023156,-0.328482,-0.302963,0.033612,-0.044965,0.045212,-0.059750,-0.000803,...,-0.010826,-0.004641,0.001286,-0.007747,0.000658,0.004775,-0.000418,0.008949,-0.000466,-0.001209
76,0.225731,-0.073319,-0.598852,-0.286496,0.518508,0.279664,-0.072499,0.097491,0.077507,0.033449,...,-0.040930,-0.000236,-0.004300,0.001249,-0.003996,0.013539,0.002262,0.005838,0.000882,0.179470
77,0.147076,-0.105782,-0.106805,-0.149092,-0.172858,-0.065525,-0.025992,-0.017902,-0.018818,0.047588,...,-0.009434,0.008315,-0.016921,0.015589,0.000570,-0.003436,-0.002333,-0.007288,0.002841,0.001701
78,0.215145,-0.273803,0.396480,-0.129897,0.263922,-0.044688,-0.118402,0.103106,-0.015408,-0.047275,...,-0.018549,0.014927,0.009150,-0.028022,0.047490,0.010152,-0.008030,-0.000370,0.002876,0.000103
79,0.527041,0.499186,0.086498,0.041854,-0.016162,0.077093,-0.036265,0.008927,0.002470,0.085482,...,-0.081318,-0.040178,0.446399,0.186215,0.060696,0.003556,0.008252,-0.000299,-0.000656,0.000460

**Modeling**

---

In [ ]:
from sklearn.linear_model import LogisticRegression

# Latih model dengan beberapa parameter
logistic_model = LogisticRegression(max_iter=1000, C=0.2)
logistic_model.fit(svd_matrix, y_train)

LogisticRegression(C=0.2, max_iter=1000)

**Evaluasi Model**

---

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

# Prediksi menggunakan data uji
y_pred = logistic_model.predict(svd_matrix)

# Menghitung akurasi
accuracy = accuracy_score(y_train, y_pred)
print(f"Akurasi: {accuracy}")

# Menampilkan classification report untuk metrik precision, recall, dan F1-score
print("\nClassification Report:")
print(classification_report(y_train, y_pred))

Akurasi: 0.825

Classification Report:
              precision    recall  f1-score   support

           0       0.75      1.00      0.86        43
           1       1.00      0.62      0.77        37

    accuracy                           0.82        80
   macro avg       0.88      0.81      0.81        80
weighted avg       0.87      0.82      0.82        80

In [ ]:
# Simpan TF-IDF vectorizer dan model
import pickle

with open('tfidf_vectorizer.pkl', 'wb') as tfidf_file:
    pickle.dump(vectorizer, tfidf_file)


with open('logistic_regression_model.pkl', 'wb') as model_file:
    pickle.dump(logistic_model, model_file)